Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BoomzGlobal.Models;

namespace BoomzGlobal.Controllers
{
    public class PackageController : Controller
    {
        private BoomzGlobalEntities db = new BoomzGlobalEntities();

        //
        // GET: /Package/

        public ActionResult Index()
        {

            ViewBag.FranchiseID = new SelectList(db.Franchise_T, "FranchiseID", "FranchiseName", "FranchiseID");
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", "CityID");


            var package_t = db.Package_T.Include(p => p.City_T).Include(p => p.Franchise_T);
            return View(package_t.ToList());
        }

        //
        // GET: /Package/Details/5

        public ActionResult Details(int id = 0)
        {
            Package_T package_t = db.Package_T.Find(id);
            if (package_t == null)
            {
                return HttpNotFound();
            }
            return View(package_t);
        }

        //
        // GET: /Package/Create

        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City");
            ViewBag.FranchiseID = new SelectList(db.Franchise_T, "FranchiseID", "CompanyName");
            return View();
        }

        //
        // POST: /Package/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Package_T package_t)
        {
            if (ModelState.IsValid)
            {
                db.Package_T.Add(package_t);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", package_t.CityID);
            ViewBag.FranchiseID = new SelectList(db.Franchise_T, "FranchiseID", "CompanyName", package_t.FranchiseID);
            return View(package_t);
        }

        //
        // GET: /Package/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Package_T package_t = db.Package_T.Find(id);
            if (package_t == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", package_t.CityID);
            ViewBag.FranchiseID = new SelectList(db.Franchise_T, "FranchiseID", "CompanyName", package_t.FranchiseID);
            return View(package_t);
        }

        //
        // POST: /Package/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Package_T package_t)
        {
            if (ModelState.IsValid)
            {
                db.Entry(package_t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", package_t.CityID);
            ViewBag.FranchiseID = new SelectList(db.Franchise_T, "FranchiseID", "CompanyName", package_t.FranchiseID);
            return View(package_t);
        }

        //
        // GET: /Package/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Package_T package_t = db.Package_T.Find(id);
            if (package_t == null)
            {
                return HttpNotFound();
            }
            return View(package_t);
        }

        //
        // POST: /Package/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Package_T package_t = db.Package_T.Find(id);
            db.Package_T.Remove(package_t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Package/Create.cshtml
@model BoomzGlobal.Models.Package_T

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Package_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.PackageID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PackageID)
            @Html.ValidationMessageFor(model => model.PackageID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseID, "Franchise_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FranchiseID", String.Empty)
            @Html.ValidationMessageFor(model => model.FranchiseID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityID, "City_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityID", String.Empty)
            @Html.ValidationMessageFor(model => model.CityID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Package)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Package)
            @Html.ValidationMessageFor(model => model.Package)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DOC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DOC)
            @Html.ValidationMessageFor(model => model.DOC)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Package/Delete.cshtml
@model BoomzGlobal.Models.Package_T

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Package_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PackageID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PackageID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Franchise_T.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Franchise_T.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City_T.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City_T.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Package)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Package)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DOC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DOC)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Package/Details.cshtml
@model BoomzGlobal.Models.Package_T

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Package_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PackageID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PackageID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Franchise_T.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Franchise_T.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City_T.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City_T.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Package)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Package)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DOC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DOC)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Package/Edit.cshtml
@model BoomzGlobal.Models.Package_T

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Package_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.PackageID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PackageID)
            @Html.ValidationMessageFor(model => model.PackageID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseID, "Franchise_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FranchiseID", String.Empty)
            @Html.ValidationMessageFor(model => model.FranchiseID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityID, "City_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityID", String.Empty)
            @Html.ValidationMessageFor(model => model.CityID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Package)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Package)
            @Html.ValidationMessageFor(model => model.Package)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DOC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DOC)
            @Html.ValidationMessageFor(model => model.DOC)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Package/Index.cshtml
@model IEnumerable<BoomzGlobal.Models.Package_T>
            
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Grocery, Food and Goods Delivery Management Web Application. Designed and Developed by BoomMaker">
    <meta name="author" content="Binju Paul">
    <meta name="keyword" content="Delivery Manager, App, Web Application, Software">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>Boomz</title>

    <script src="~/js/jquery-1.8.3.min.js"></script>
    <!-- Bootstrap core CSS -->
    <script src="~/js/jquery.dcjqaccordion.2.7.min.js"></script>

    <script src="~/js/jquery.scrollTo.min.js"></script>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="~/js/html5shiv.js"></script>
      <script src="~/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <section id="container" class="">
        <!--header start-->
        @Html.Partial("_Header")
        <!--header end-->
        <!--sidebar start-->
        <aside>
            @Html.Partial("_Menu")
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <!-- page start-->

                <div class="row" style="min-height:600px;">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                              Package
                                <button id="add" class="btn btn-danger btn-xs pull-right"><i class="fa fa-plus"></i>Add Package</button>
<br /> 
                                
                            </header>
                            
                                                      
                            
                            <script>
                                $(document).ready(function () {
                                    $("#addform,.editrow").hide();
                                    $("#add").click(function () {
                                        $("#addform").show(2000);
                                    });


                                });
                                function openrow(row) {
                                    $("#edit-" + row).show(2000);

                                }
                                
                            </script>

                            <div id="addform" style="height:200px; width:100%;padding:25px; ">

                                @using (Html.BeginForm("Create", "Package"))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                <p>Add a package to a Franchise (select franchise) or Add package for the Website (Select City)     </p>
                                    <div class="col-lg-8 pull-left">
                                        Franchise <br />
                                        @Html.DropDownList("FranchiseID", String.Empty)<br />

                                        City <br />
                                        @Html.DropDownList("CityID", String.Empty)<br />
                                        
                                        Package<br />
                                        <input type="text" name="Package" class="form-control cke_required" /><br />

                                        
                                         
                                         
                                    </div>
                                    <br />
                                    <input type="submit" name="submit" class="btn btn-warning" value="Save" />
                                }
                            </div>

                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th><i class="fa fa-sort"></i> Franchise</th>
                                        <th><i class="fa fa-sort"></i> City</th>
                                        <th><i class="fa fa-sort"></i> Package</th>
                                       
                                        <th>Modify</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.Franchise_T.FranchiseName
                                            </td>
                                            <td>
                                                @item.City_T.City
                                            </td>
                                            <td>
                                                @item.Package
                                            </td>

                                            <td>

                                                <button onclick="openrow(@item.PackageID)" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>

                                            </td>
                                        </tr>
                                        using (Html.BeginForm("Edit", "Package"))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.ValidationSummary(true)
                                            <tr id="edit-@item.PackageID" class="editrow">
                                                <td>
                                                    @Html.DropDownList("FranchiseID", String.Empty)
                                                </td>
                                                <td>
                                                    @Html.DropDownList("CityID", String.Empty)
                                                </td>
                                                <td>

                                                    <input class="form-control cke_required" type="text" name="Package" value="@item.Package" />
                                                    <input  type="hidden" name="PackageID" value="@item.PackageID" />
                                                    </td>
                                                
                                                <td>

                                                    <button class="btn btn-danger btn-xs"><i class="fa fa-pencil"></i> Update</button>

                                                </td>
                                            </tr>
                                        }

                                    }
                                </tbody>
                            </table>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/respond.min.js"></script>
    <!--common script for all pages-->
    <script src="~/js/common-scripts.js"></script>
    <script>
    $("select").addClass("form-control");
    </script>
</body>
</html>

Views/Package/Index5455.cshtml
@model IEnumerable<BoomzGlobal.Models.Package_T>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PackageID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Franchise_T.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City_T.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Package)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PackageID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Franchise_T.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City_T.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Package)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>