Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BoomzGlobal.Models;

namespace BoomzGlobal.Controllers
{
    public class CountryController : Controller
    {
        private BoomzGlobalEntities db = new BoomzGlobalEntities();

        //
        // GET: /Country/

        public ActionResult Index()
        {
            return View(db.Country_T.ToList());
        }

        //
        // GET: /Country/Details/5

        public ActionResult Details(int id = 0)
        {
            Country_T country_t = db.Country_T.Find(id);
            if (country_t == null)
            {
                return HttpNotFound();
            }
            return View(country_t);
        }

        //
        // GET: /Country/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Country/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Country_T country_t)
        {
          
                db.Country_T.Add(country_t);
                db.SaveChanges();
                return RedirectToAction("Index");
             

           
        }

        //
        // GET: /Country/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Country_T country_t = db.Country_T.Find(id);
            if (country_t == null)
            {
                return HttpNotFound();
            }
            return View(country_t);
        }

        //
        // POST: /Country/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Country_T country_t)
        {
            
                db.Entry(country_t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
             
           
        }

        //
        // GET: /Country/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Country_T country_t = db.Country_T.Find(id);
            if (country_t == null)
            {
                return HttpNotFound();
            }
            return View(country_t);
        }

        //
        // POST: /Country/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country_T country_t = db.Country_T.Find(id);
            db.Country_T.Remove(country_t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Country/Create.cshtml
@model BoomzGlobal.Models.Country_T

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Country_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CountryID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CountryID)
            @Html.ValidationMessageFor(model => model.CountryID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Country)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Country)
            @Html.ValidationMessageFor(model => model.Country)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Country/Delete.cshtml
@model BoomzGlobal.Models.Country_T

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Country_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CountryID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CountryID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Country/Details.cshtml
@model BoomzGlobal.Models.Country_T

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Country_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CountryID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CountryID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Country/Edit.cshtml
@model BoomzGlobal.Models.Country_T

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Country_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CountryID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CountryID)
            @Html.ValidationMessageFor(model => model.CountryID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Country)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Country)
            @Html.ValidationMessageFor(model => model.Country)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Country/Index.cshtml
@model IEnumerable<BoomzGlobal.Models.Country_T>
            
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Grocery, Food and Goods Delivery Management Web Application. Designed and Developed by BoomMaker">
    <meta name="author" content="Binju Paul">
    <meta name="keyword" content="Delivery Manager, App, Web Application, Software">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>Boomz</title>

    <script src="~/js/jquery-1.8.3.min.js"></script>
    <!-- Bootstrap core CSS -->
    <script src="~/js/jquery.dcjqaccordion.2.7.min.js"></script>

    <script src="~/js/jquery.scrollTo.min.js"></script>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="~/js/html5shiv.js"></script>
      <script src="~/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <section id="container" class="">
        <!--header start-->
        @Html.Partial("_Header")
        <!--header end-->
        <!--sidebar start-->
        <aside>
            @Html.Partial("_Menu")
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <!-- page start-->

                <div class="row" style="min-height:600px;">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                               COUNTRY
                                <button id="add" class="btn btn-danger btn-xs pull-right"><i class="fa fa-plus"></i> Add Country</button>
<br />
                            </header>
                            
                                
                            
                            <script>
                                $(document).ready(function () {
                                    $("#addform,.editrow").hide();
                                    $("#add").click(function () {
                                        $("#addform").show(2000);
                                    });


                                });
                                function openrow(row) {
                                    $("#edit-" + row).show(2000);

                                }
                            </script>

                            <div id="addform" style="height:90px; width:100%;padding:25px; ">

                                @using (Html.BeginForm("Create", "Country"))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)

                                    <div class="col-lg-8 pull-left">
                                        Country<br />
                                        <input type="text" name="Country" class="form-control cke_required" />
                                         
                                         
                                    </div>
                                    <br />
                                    <input type="submit" name="submit" class="btn btn-warning" value="Save" />
                                }
                            </div>

                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th><i class="fa fa-sort"></i> Country</th>
                                       
                                        <th>Modify</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.Country
                                            </td>
                                             

                                            <td>

                                                <button onclick="openrow(@item.CountryID)" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>

                                            </td>
                                        </tr>
                                        using (Html.BeginForm("Edit", "Country"))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.ValidationSummary(true)
                                            <tr id="edit-@item.CountryID" class="editrow">
                                                <td>
                                                    <input class="form-control cke_required" type="text" name="Country" value="@item.Country" />
                                                    <input  type="hidden" name="CountryID" value="@item.CountryID" />
                                                    </td>
                                                
                                                <td>

                                                    <button class="btn btn-danger btn-xs"><i class="fa fa-pencil"></i> Update</button>

                                                </td>
                                            </tr>
                                        }

                                    }
                                </tbody>
                            </table>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                Designed & Developed by elanDc
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/respond.min.js"></script>
    <!--common script for all pages-->
    <script src="~/js/common-scripts.js"></script>

</body>
</html>

Views/Country/Indexdfdf.cshtml
@model IEnumerable<BoomzGlobal.Models.Country_T>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CountryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CountryID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>