Controllers/FranchiseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BoomzGlobal.Models;

namespace BoomzGlobal.Controllers
{
    public class FranchiseController : Controller
    {
        private BoomzGlobalEntities db = new BoomzGlobalEntities();

        //
        // GET: /Franchise/

        public ActionResult Index()
        {
            var franchise_t = db.Franchise_T.Include(f => f.City_T).Include(f => f.Country_T);
            return View(franchise_t.ToList());
        }

        //
        // GET: /Franchise/Details/5

        public ActionResult Details(int id = 0)
        {
            Franchise_T franchise_t = db.Franchise_T.Find(id);
            if (franchise_t == null)
            {
                return HttpNotFound();
            }
            return View(franchise_t);
        }

        //
        // GET: /Franchise/Create

        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City");
            ViewBag.CountryID = new SelectList(db.Country_T, "CountryID", "Country");
            return View();
        }

        //
        // POST: /Franchise/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Franchise_T franchise_t)
        {
            if (ModelState.IsValid)
            {
                db.Franchise_T.Add(franchise_t);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", franchise_t.CityID);
            ViewBag.CountryID = new SelectList(db.Country_T, "CountryID", "Country", franchise_t.CountryID);
            return View(franchise_t);
        }

        //
        // GET: /Franchise/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Franchise_T franchise_t = db.Franchise_T.Find(id);
            if (franchise_t == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", franchise_t.CityID);
            ViewBag.CountryID = new SelectList(db.Country_T, "CountryID", "Country", franchise_t.CountryID);
            return View(franchise_t);
        }

        //
        // POST: /Franchise/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Franchise_T franchise_t)
        {
            if (ModelState.IsValid)
            {
                db.Entry(franchise_t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.City_T, "CityID", "City", franchise_t.CityID);
            ViewBag.CountryID = new SelectList(db.Country_T, "CountryID", "Country", franchise_t.CountryID);
            return View(franchise_t);
        }

        //
        // GET: /Franchise/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Franchise_T franchise_t = db.Franchise_T.Find(id);
            if (franchise_t == null)
            {
                return HttpNotFound();
            }
            return View(franchise_t);
        }

        //
        // POST: /Franchise/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Franchise_T franchise_t = db.Franchise_T.Find(id);
            db.Franchise_T.Remove(franchise_t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Franchise/Create.cshtml
@model BoomzGlobal.Models.Franchise_T

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Franchise_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FranchiseID)
            @Html.ValidationMessageFor(model => model.FranchiseID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CountryID, "Country_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CountryID", String.Empty)
            @Html.ValidationMessageFor(model => model.CountryID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityID, "City_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityID", String.Empty)
            @Html.ValidationMessageFor(model => model.CityID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FranchiseName)
            @Html.ValidationMessageFor(model => model.FranchiseName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telephone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telephone)
            @Html.ValidationMessageFor(model => model.Telephone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactPerson1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactPerson1)
            @Html.ValidationMessageFor(model => model.ContactPerson1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mobile1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mobile1)
            @Html.ValidationMessageFor(model => model.Mobile1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email1)
            @Html.ValidationMessageFor(model => model.Email1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactPerson2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactPerson2)
            @Html.ValidationMessageFor(model => model.ContactPerson2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mobile2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mobile2)
            @Html.ValidationMessageFor(model => model.Mobile2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email2)
            @Html.ValidationMessageFor(model => model.Email2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DOC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DOC)
            @Html.ValidationMessageFor(model => model.DOC)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Franchise/Delete.cshtml
@model BoomzGlobal.Models.Franchise_T

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Franchise_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FranchiseID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FranchiseID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country_T.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country_T.Country)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City_T.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City_T.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FranchiseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FranchiseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Telephone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telephone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactPerson1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactPerson1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mobile1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mobile1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactPerson2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactPerson2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mobile2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mobile2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DOC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DOC)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Franchise/Details.cshtml
@model BoomzGlobal.Models.Franchise_T

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Franchise_T</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FranchiseID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FranchiseID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country_T.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country_T.Country)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City_T.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City_T.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FranchiseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FranchiseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Telephone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telephone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactPerson1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactPerson1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mobile1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mobile1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactPerson2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactPerson2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mobile2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mobile2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DOC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DOC)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Franchise/Edit.cshtml
@model BoomzGlobal.Models.Franchise_T

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Franchise_T</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FranchiseID)
            @Html.ValidationMessageFor(model => model.FranchiseID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CountryID, "Country_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CountryID", String.Empty)
            @Html.ValidationMessageFor(model => model.CountryID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityID, "City_T")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityID", String.Empty)
            @Html.ValidationMessageFor(model => model.CityID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FranchiseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FranchiseName)
            @Html.ValidationMessageFor(model => model.FranchiseName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Telephone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Telephone)
            @Html.ValidationMessageFor(model => model.Telephone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactPerson1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactPerson1)
            @Html.ValidationMessageFor(model => model.ContactPerson1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mobile1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mobile1)
            @Html.ValidationMessageFor(model => model.Mobile1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email1)
            @Html.ValidationMessageFor(model => model.Email1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactPerson2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactPerson2)
            @Html.ValidationMessageFor(model => model.ContactPerson2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mobile2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mobile2)
            @Html.ValidationMessageFor(model => model.Mobile2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email2)
            @Html.ValidationMessageFor(model => model.Email2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DOC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DOC)
            @Html.ValidationMessageFor(model => model.DOC)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Franchise/Index.cshtml
@model IEnumerable<BoomzGlobal.Models.Franchise_T>
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Grocery, Food and Goods Delivery Management Web Application. Designed and Developed by BoomMaker">
    <meta name="author" content="Binju Paul">
    <meta name="keyword" content="Delivery Manager, App, Web Application, Software">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>Boomz</title>

    <script src="~/js/jquery-1.8.3.min.js"></script>
    <!-- Bootstrap core CSS -->
    <script src="~/js/jquery.dcjqaccordion.2.7.min.js"></script>

    <script src="~/js/jquery.scrollTo.min.js"></script>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="~/js/html5shiv.js"></script>
      <script src="~/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <section id="container" class="">
        <!--header start-->
        @Html.Partial("_Header")
        <!--header end-->
        <!--sidebar start-->
        <aside>
            @Html.Partial("_Menu")
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <!-- page start-->

                <div class="row" style="min-height:600px;">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                              Franchise
                                <button id="add" class="btn btn-danger btn-xs pull-right"><i class="fa fa-plus"></i>Add Franchise</button>
<br /> 
                                
                            </header>
                            
                                                      
                            
                            <script>
                                $(document).ready(function () {
                                    $("#addform,.editrow").hide();
                                    $("#add").click(function () {
                                        $("#addform").show(2000);
                                    });


                                });
                                function openrow(row) {
                                    $("#edit-" + row).show(2000);

                                }
                                
                            </script>

                            <div id="addform" style="height:200px; width:100%;padding:25px; ">

                                @using (Html.BeginForm("Create", "Franchise"))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)
                                <p>Add a Franchise to a Franchise (select franchise) or Add Franchise for the Website (Select City)     </p>
                                    <div class="col-lg-8 pull-left">
                                        Franchise <br />
                                        

                                        City <br />
                                       
                                        
                                        Franchise<br />
                                        <input type="text" name="Franchise" class="form-control cke_required" /><br />

                                        
                                         
                                         
                                    </div>
                                    <br />
                                    <input type="submit" name="submit" class="btn btn-warning" value="Save" />
                                }
                            </div>

                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th><i class="fa fa-sort"></i> Franchise</th>
                                        <th><i class="fa fa-sort"></i> City</th>
                                        <th><i class="fa fa-sort"></i> Franchise</th>
                                       
                                        <th>Modify</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  
                                        
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                          
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Country_T.Country)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.City_T.City)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.FranchiseName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Telephone)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Password)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Website)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ContactPerson1)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Mobile1)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email1)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ContactPerson2)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Mobile2)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email2)
                                                </td>
                                   
                                   
                                            </tr>
                                        
                                        using (Html.BeginForm("Edit", "Franchise"))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.ValidationSummary(true)
                                            <tr id="edit-@item.FranchiseID" class="editrow">
                                                <td>
                                                 
                                                </td>
                                                <td>
                                                  
                                                </td>
                                                <td>

                                                    <input class="form-control cke_required" type="text" name="Franchise" value="@item.FranchiseName" />
                                                    <input  type="hidden" name="FranchiseID" value="@item.FranchiseID" />
                                                    </td>
                                                
                                                <td>

                                                    <button class="btn btn-danger btn-xs"><i class="fa fa-pencil"></i> Update</button>

                                                </td>
                                            </tr>
                                        }

                                        }
                                </tbody>
                            </table>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/respond.min.js"></script>
    <!--common script for all pages-->
    <script src="~/js/common-scripts.js"></script>
    <script>
    $("select").addClass("form-control");
    </script>
</body>
</html>